@startuml
'https://plantuml.com/sequence-diagram

autonumber

SS -> QP: NeedRewrite
alt NeedRewrite is false
SS <-- QP: respond nil rewrite result
else NeedRewrite is true
QP -> QP: Get WSRP/NSRP config from edison
QP -> QP: compose handle func according to config
loop handle func list
QP -> QP: execute handle func
alt has result
SS <-- QP: respond result if one handler has result and break
end
end
SS <-- QP: respond nil
end
@enduml